name: Rotate Postgres (Create, Restore, Switch)

on:
  workflow_dispatch:
    inputs:
      rotate_after_days:
        description: Rotate if current DB age >= this many days
        required: false
        type: string
      db_name_suffix:
        description: Suffix for new DB name (defaults to timestamp)
        required: false
        type: string

jobs:
  rotate:
    runs-on: ubuntu-latest

    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      RENDER_BACKEND_SERVICE_ID: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
      RENDER_RESTORE_SERVICE_ID: ${{ secrets.RENDER_RESTORE_SERVICE_ID }}

      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
      EMAIL_API_URL: ${{ secrets.EMAIL_API_URL }}
      EMAIL_API_KEY: ${{ secrets.EMAIL_API_KEY }}

      RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
      GDRIVE_REMOTE: ${{ secrets.GDRIVE_REMOTE }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq coreutils

      - name: Detect current DB name
        id: dbname
        run: |
          NAME=$(awk '
            /name: vivekanand-manager-backend/{inSvc=1}
            inSvc && /- key: DB_URL/{inDb=1}
            inDb && /name:/{print $2; exit}
          ' render.yaml)

          [ -z "$NAME" ] && { echo "DB name not found"; exit 1; }
          echo "CURRENT_DB_NAME=$NAME" >> "$GITHUB_OUTPUT"

      - name: Calculate DB age
        id: dbage
        run: |
          RESP=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" \
            https://api.render.com/v1/services?limit=100)

          CREATED=$(echo "$RESP" | jq -r '.[] |
            select(.service.name=="'${{ steps.dbname.outputs.CURRENT_DB_NAME }}'") |
            .service.createdAt')

          [ -z "$CREATED" ] && exit 1

          AGE=$(( ( $(date -u +%s) - $(date -u -d "$CREATED" +%s) ) / 86400 ))
          echo "AGE_DAYS=$AGE" >> "$GITHUB_OUTPUT"

      - name: Decide rotation
        id: decision
        run: |
          LIMIT="${{ github.event.inputs.rotate_after_days }}"
          AGE="${{ steps.dbage.outputs.AGE_DAYS }}"

          if [ -z "$LIMIT" ] || [ "$AGE" -ge "$LIMIT" ]; then
            echo "ROTATE=yes" >> "$GITHUB_OUTPUT"
          else
            echo "ROTATE=no" >> "$GITHUB_OUTPUT"
          fi

      - name: Exit if no rotation
        if: ${{ steps.decision.outputs.ROTATE != 'yes' }}
        run: echo "Skipping rotation"

      - name: Create new DB + update render.yaml
        if: ${{ steps.decision.outputs.ROTATE == 'yes' }}
        id: newdb
        run: |
          SUFFIX="${{ github.event.inputs.db_name_suffix }}"
          [ -z "$SUFFIX" ] && SUFFIX=$(date +%Y%m%d%H%M)

          NEW_DB="vivekanand-manager-db-$SUFFIX"
          echo "NEW_DB_RES_NAME=$NEW_DB" >> "$GITHUB_OUTPUT"

          cat >> render.yaml <<'EOF'

            - name: __NEW_DB_NAME__
              plan: free
              region: singapore
              ipAllowList:
                - source: 0.0.0.0/0
                  description: everywhere
              postgresMajorVersion: "18"
          EOF

          sed -i "s/__NEW_DB_NAME__/$NEW_DB/" render.yaml

          sed -i "/vivekanand-manager-backend/,/- key:/{
            s/name: ${{ steps.dbname.outputs.CURRENT_DB_NAME }}/name: $NEW_DB/
          }" render.yaml

      - name: Commit blueprint changes
        if: ${{ steps.decision.outputs.ROTATE == 'yes' }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add render.yaml
          git commit -m "rotate-db: switch to ${{ steps.newdb.outputs.NEW_DB_RES_NAME }}"
          git push

      - name: Wait for provisioning
        if: ${{ steps.decision.outputs.ROTATE == 'yes' }}
        run: sleep 300

      - name: Verify backend health
        if: ${{ steps.decision.outputs.ROTATE == 'yes' }}
        run: |
          URL="https://vivekanand-manager-backend.onrender.com/actuator/health"
          for i in {1..40}; do
            code=$(curl -s -o /dev/null -w '%{http_code}' "$URL")
            echo "Health: $code"
            [ "$code" = "200" ] && exit 0
            sleep 10
          done
          exit 1
