
name: Sync Env Vars to Render & Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      RENDER_BACKEND_SERVICE_ID: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
      RENDER_FRONTEND_SERVICE_ID: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}

      # Backend secrets (GitHub-only)
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
      EMAIL_API_URL: ${{ secrets.EMAIL_API_URL }}
      EMAIL_API_KEY: ${{ secrets.EMAIL_API_KEY }}

      # Frontend (Vite)
      VITE_API_URL: ${{ secrets.VITE_API_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Build backend env payload
        run: |
          cat > backend_env.json <<EOF
          [
            {"key":"SPRING_PROFILES_ACTIVE","value":"prod"},
            {"key":"SPRING_APP_NAME","value":"Vivekanand-Manager"},
            {"key":"PORT","value":"10000"},
            {"key":"SWAGGER_UI_PATH","value":"/swagger-ui.html"},
            {"key":"SPRINGDOC_API_ENABLED","value":"true"},
            {"key":"JPA_DDL_AUTO","value":"update"},
            {"key":"JPA_SHOW_SQL","value":"false"},
            {"key":"HIBERNATE_FORMAT_SQL","value":"true"},
            {"key":"MULTIPART_MAX_FILE_SIZE","value":"100MB"},
            {"key":"MULTIPART_MAX_REQUEST_SIZE","value":"100MB"},
            {"key":"UPLOAD_DIR","value":"/app/uploads"},
            {"key":"UPLOAD_MAX_MB","value":"100"},
            {"key":"JWT_SECRET","value":"${JWT_SECRET}"},
            {"key":"CLOUDINARY_API_KEY","value":"${CLOUDINARY_API_KEY}"},
            {"key":"CLOUDINARY_API_SECRET","value":"${CLOUDINARY_API_SECRET}"},
            {"key":"CLOUDINARY_CLOUD_NAME","value":"${CLOUDINARY_CLOUD_NAME}"},
            {"key":"CORS_ALLOWED_ORIGINS","value":"${CORS_ALLOWED_ORIGINS}"},
            {"key":"EMAIL_API_URL","value":"${EMAIL_API_URL}"},
            {"key":"EMAIL_API_KEY","value":"${EMAIL_API_KEY}"}
            # DB_URL/USER/PASS remain fromDatabase per render.yaml
          ]
          EOF

      - name: PUT backend env vars (replace set)
        run: |
          curl --fail -X PUT "https://api.render.com/v1/services/${RENDER_BACKEND_SERVICE_ID}/env-vars" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            --data-binary @backend_env.json

      - name: Build frontend env payload
        run: |
          cat > frontend_env.json <<EOF
          [
            {"key":"VITE_API_URL","value":"${VITE_API_URL}"}
          ]
          EOF

      - name: PUT frontend env vars
        run: |
          curl --fail -X PUT "https://api.render.com/v1/services/${RENDER_FRONTEND_SERVICE_ID}/env-vars" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            --data-binary @frontend_env.json

      - name: Trigger backend deploy
        run: |
          curl --fail -X POST "https://api.render.com/v1/services/${RENDER_BACKEND_SERVICE_ID}/deploys" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache":"do_not_clear"}'

      - name: Trigger frontend deploy
        run: |
          curl --fail -X POST "https://api.render.com/v1/services/${RENDER_FRONTEND_SERVICE_ID}/deploys" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache":"do_not_clear"}'

      - name: Verify backend health
        run: |
          BACKEND_URL="https://vivekanand-manager-backend.onrender.com/actuator/health"
          for i in {1..40}; do
            CODE=$(curl -s -o /dev/null -w '%{http_code}' "$BACKEND_URL")
            echo "Health HTTP $CODE"
            if [ "$CODE" = "200" ]; then exit 0; fi
            sleep 10
          done
          echo "Backend did not become healthy in time"; exit 1
